name: Continuous_Development

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Set user and email
        run: |
          git config --global user.email "${github.actor}@users.noreply.github.com"
          git config --global user.name "${github.actor}"

      - name: Build & deploy
        run: yarn deploy
